quarkus.http.port=9091
quarkus.http.host=0.0.0.0


quarkus.datasource.db-kind=mysql 
quarkus.datasource.username=root
quarkus.datasource.password=password12

quarkus.datasource.jdbc.url=jdbc:mysql://192.168.11.210:3306/testDB
quarkus.datasource.jdbc.max-size=16